name: 'dotnet_checkout_pack_push'
description: 'checkout dotnet source and pack and then push to nuget'

inputs:
  dotnet-version:
    required: false
    default: '6.0.x'

  project-path:
    description: 'path to project (csproj) directory or file if one of the project needed'
    required: false
    default: '.'

  nuget-api-key:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: pack
      shell: bash
      run: dotnet pack ${{ inputs.project-path }} -c Release -p:ContinuousIntegrationBuild=true

    - name: push
      shell: bash
      run: find . -iname *.nupkg -exec dotnet nuget push {} --api-key ${{ inputs.nuget-api-key }} \;
