name: 'dotnet_checkout_pack_push'
description: 'checkout dotnet source and pack and then push to nuget'

inputs:
  dotnet-version:
    required: false
    default: '6.0.x'

  project-path:
    description: 'path to project (csproj) directory or file if one of the project needed'
    required: false
    default: '.'

  nuget-api-url:
    required: false
    default: 'https://api.nuget.org/v3/index.json'

  nuget-api-key:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: pack
      shell: bash
      run: dotnet pack ${{ inputs.project-path }} -c Release -p:ContinuousIntegrationBuild=true --verbosity normal

    - name: push
      shell: bash
      run: set -e && shopt -s globstar && for f in  **/*.nupkg; do dotnet nuget push $f --source ${{ inputs.nuget-api-url }} --api-key ${{ inputs.nuget-api-key }}; done
